version: '3.8'

services:
  ubuntu_ssh:
    image: ubuntu
    container_name: telua_sqlalchemy
    ports:
      - "2222:22"
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - ./test.py:/etc/ssh/sshd_config
    stdin_open: true
    tty: true
